language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: cb4d9f7a6aa940f06b0bb045b27ffd39df0014796dcc137b6cac45004fce2d94
script: yarn run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
  - bash travis-after-build.sh
